# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/wixcore/blog/models/post/columns.yaml

# Filter widget configuration
filter: $/wixcore/blog/models/post/scopes.yaml

# Model Class name
modelClass: WixCore\Blog\Models\Post

# List Title
title: wixcore.blog::lang.posts.list_title

# Link URL for each record
recordUrl: wixcore/blog/posts/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 25

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: published_at
    direction: desc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
